Para copiar automáticamente los logs de la API de un contenedor Docker hacia el disco duro local, puedes seguir estos pasos:

Add a line to copy the logs from the location in the container to a specific location within the container where Docker can mount a volume.


# Add this to the Dockerfile
```bash
COPY /path/to/the/logs /path/in/the/container
```
When you run the container, you will need to set up a volume so that Docker can mount the directory where the logs will be copied to your local hard drive.

```bash
docker run -v /path/local:/path/to/the/container name-of-your-image
```

In this way, the logs generated by the API in the container will be automatically copied to the directory on your local hard drive that you have specified.
